### ISSUE TITLE
Gigasecond unit tests don't include the proper boost headers

### ISSUE THREAD

**Issue by hpwooten-wta** [exercism/cpp#142]
In the test suite for gigasecond, the compiler emits errors about not finding the types from boost.dateTime. This is because the proper header isn't included. I can see two ways forward for this:

1. Don't do anything. Having to debug this issue was a good exercise, because it taught me to remember to check the headers (which have to be used in the user-provided gigasecond.h anyway). 
2. Include the headers into the test suite. The user will still need to include the header in their own solution files, so they'll still get that practice.

**Comment by patricksjackson** [comment]
I don't remember this being an issue when I did the problem, but I don't usually try to compile an empty solution. I understand many people do though, which is one reason why we've been adding some of the `std` includes needed by the test suite. ( #121 )

This one is a bit different though, since reading the Boost docs (with the link given in the test suite) and then writing the obvious 1 liner is the entire exercise. Giving them the right header in the test suite lets the user avoid the issue of figuring out what include file they need.

I think it's better to leave as is. Thanks for bringing it up though :) 

(If you do feel strongly that it should be in there, reopen and we can discuss more. These types of discussions about improving the test suite are really valuable to have. )

**Comment by hpwooten-wta** [comment]
I was torn on whether including the header would be better or worse, so thanks for your input. I agree with this decision.
