### ISSUE TITLE
Lots of noise in git when running tests

### ISSUE THREAD

**Issue by elyashiv** [exercism/cpp#226]
If I run tests locally on my machine, I get a lot of noise - all the example files are renamed.

Can we copy them instead of renaming, then add them to the .gitignore?

**Comment by KevinWMatthews** [comment]
That's a good idea.

Thoughts:

Need to look into how CMake supports `file(COPY)` instead of `file(RENAME)`.

I wonder if we could symlink? Hmmm.... I don't know how to test that cross-platform.

Would you update the root-level `.gitignore` or add a .gitignore to each directory?
We'd need to be sure that the user doesn't download the `.gitignore` file - that could be frustrating.

I don't know of any way that `.gitignore` supports advanced pattern matching, so we might need to configure each exercise by hand. Can you think of another way?

Are there consequences to editing the `.gitignore` that I'm not thinking about? Maybe just copying is enough? It might be nice to know that copied files are present.

**Comment by KevinWMatthews** [comment]
As far as I can tell, CMake's `file(COPY)` does not support renames during a copy. This is trickier than I expected.

**Comment by patricksjackson** [comment]
I'll note here, the other thing to remember is that some exercises have a skeleton header file that is delivered to the student, so we're actually overwriting those files. (One of the quirks of exercism. It downloads everything to the student except files that start with "example", as far as I remember. I think it would download a .gitignore if it was in the exercise directory.)

I feel this pain too while developing. Two thoughts (I don't have time to look myself right now).

1. Does the new cmake support running in a build/ subdirectory from the root?
2. Can we just setup the root cmake to create a parallel tree of exercises/ that we could gitignore?

I would advise against trying to symlink and deal with the cross-platform issues that would come out of that.

**Comment by elyashiv** [comment]
I like the idea of another tree.

The gitignore can be contain something like:
```
*
!CmakeLists.txt
!example.*
```
But that will ignore also the skeleton files...

**Comment by KevinWMatthews** [comment]
@patricksjackson Yes, CMake does support running in a `build/` subdirectory. You can run it anywhere, for that matter. I'm currently running a true out-of-tree build (`build/` is at the same level as `cpp/`) and it works quite nicely.

I'm glad you mentioned the skeleton header files. I only see one? But it's an important one: `hello_world.h`.

I like the idea of a parallel exercise tree. It might seem strange at first, but we do have an atypical use case. I wrote up a paragraph of ideas, but I'll just go try them and report back.

@elyashiv That `.gitignore` would probably work, but it could also be frustrating to newcomers. They may not know about the "ignore everything" policy and could be quite confused that new files don't show up. Thoughts?

**Comment by KevinWMatthews** [comment]
Should be fixed by #228
