### ISSUE TITLE
test_hamming does not compile

### ISSUE THREAD

**Issue by matlag** [exercism/cpp#268]
Hello!

I was desperate about finding out what I was doing wrong, and I finally tried with the example.c and example.h found on GitHub:

OS: Ubuntu 18.04 (LTS) + KDE Neon (though should be irrelevant, I'm doing all in a console right now)

```
$g++ --version:
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

$make --version:
GNU Make 4.1
Construit pour x86_64-pc-linux-gnu

$make test_hamming &> test_hamming_compilation_log

```

[test_hamming_compilation_log.txt](https://github.com/exercism/cpp/files/3087586/test_hamming_compilation_log.txt)

Let me know if you need more info (or if I'm really doing something wrong... /o\)

**Comment by patricksjackson** [comment]
Can you try cloning and building this repo? I suspect you may have a mismatch with the test file and examples, since we updated that exercise to Catch 11 days ago.

If this fails I am very interested, because it shouldn't be failing. We test the stuff in this repo a lot.

```
git clone https://github.com/exercism/cpp.git cpp
cd cpp
cmake .
make test_hamming
```

From the error log it's looking for std:: stuff in "hamming::std", so maybe you changed the files in some way? If the above works that means you either have a mismatch or one of the files (CMakeLists.txt or the source files) has been changed.

**Comment by matlag** [comment]
Aaargh!
It compiles!

And the problem is actually indeed on me: I tried to move away and recreate the exercise directory before submitting this report and I did the very same mistake twice:
I create a namespace and I don't close its definition... :|

My bad and sorry for the noise! I'm closing this issue.

**Comment by patricksjackson** [comment]
No problem, it happens. Also a 40,000 line error message because you forgot a bracket is certainly a little intimidating...

I suggest when you get these issues looking at the first one that comes up, sometimes it's easier to figure out what's wrong from that.

Thanks :)
