### ISSUE TITLE
Atbash Cipher (Own Version)

### ISSUE THREAD

**Issue by InVaedar** [exercism/cpp#269]
Hi. I have created an Atbash Cipher, based on your Atbash Cipher Explanation. But it is not working properly. Letters a - m is being encrypted properly, but letters n-z is not being encrypted. What should I do next?
Code: 
```cpp
#include <iostream>
#include <string>
using namespace std;
int main() {
    string RealAlpha ="abcdefghijklmnopqrstuvwxyz";
    string RevAlpha = "zyxwvutsrqponmlkjihgfedcba";
    string word;
    cout << "Enter word: ";getline(cin,word);
    for(int i = 0;i < word.length(); ++i){
        for(int j = 0;j <= 13;j++){
            if(word[i] == RealAlpha[j]){
                word[i] = RevAlpha[j];
            }
        }
    }
    cout << word << endl;
    return 0;
}
```
Output: 
Enter word: hello
svooo(should be svool since l = o, and o = l)

**Comment by patricksjackson** [comment]
You could always try working through [our test suite](https://github.com/exercism/cpp/blob/master/exercises/atbash-cipher/atbash_cipher_test.cpp) to find the bug. Exercism uses [TDD](https://medium.freecodecamp.org/test-driven-development-what-it-is-and-what-it-is-not-41fa6bca02a2) primarily as a teaching tool, but it's also pretty useful for finding bugs.

Failing that, you can upload a non-working solution to exercism.io to get feedback from a mentor.

Or, since [I see](https://github.com/InVaedar/projects/blob/master/Atbash%20Cipher.cpp) you already fixed it, here's a couple ways you might make it better:
1. Use magic numbers as little as possible, so replace `13` with the length of the string, `RealAlpha.length()`.
2. Try doing it without using 4 copies of the alphabet, you actually don't need any of them.
