### ISSUE TITLE
Setting up the 1st exercise using Visual Studio 2019 for C++, Boost, Windows 10

### ISSUE THREAD

**Issue by rotsoc** [exercism/cpp#270]
For the 1st exercise, I created a .cpp file which has a function `hello()` which prints "Hello, World!". 
In order to build, I opened a powershell in the folder directory, and ran `mkdir build`, `cd build`, and `cmake -G "Visual Studio 16" ..`.
Then I tried to run `cmake --build . --target ALL_BUILD --config Debug` but I get the following error: `hello_world_test.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<
char>,class std::allocator<char> > __cdecl hello_world::hello(void)" (?hello@hello_world@@YA?AV?$basic_string@DU?$char_
traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "void __cdecl ____C_A_T_C_H____T_E_S_T____0(void)" (?__
__C_A_T_C_H____T_E_S_T____0@@YAXXZ) [C:\Users\User\Exercism\cpp\hello-world\build\hello-world.vcxproj]
C:\Users\User\Exercism\cpp\hello-world\build\Debug\hello-world.exe : fatal error LNK1120: 1 unresolved externals [C:\Us
ers\User\Exercism\cpp\hello-world\build\hello-world.vcxproj]`
I guess there is some problem either with the way I am trying to run the program or with the testing using Boost. Maybe I just wrote some wrong code, though?
I could use some help... thank you!

**Comment by patricksjackson** [comment]
We're changing things here to make things easier, but you've been caught in between our updates and the doc changes unfortunately. See #267 which changes those helper docs a lot. We removed (or have almost finished removing) Boost from almost every exercise, so the docs needed an update.

The doc changes can be a bit tricky to view, so I've copied the new Windows instructions here:

Windows users can get [Visual Studio Community](https://www.visualstudio.com/vs/community/), a free download that will give you the Visual Studio IDE and the latest version of the Microsoft Visual C++ compiler.

1. Follow [the instructions here](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio) to setup CMake.
1. Download the exercise using the [exercism cli](https://exercism.io/cli-walkthrough) tool.
1. Open Visual Studio 2017 or higher (With Visual C++ tools for CMake installed as described from the link above).
1. Open the exercise folder in VS.
1. Run "Build->Build the solution". The tests will execute with the build, with the output going to the build window. Since the test runs during the build, VS will say it is a build failure if one of the tests fail, and the test failure messages will be in the build output window.

**Comment by rotsoc** [comment]
Thank you! This is much easier!
By the way, if anyone else stumbles upon this issue, the error was due to an actual error in the code I wrote!

**Comment by patricksjackson** [comment]
@rotsoc Let me know if you have any issues with the new way. We always want to get feedback from people new to the language and environment, since we aren't always sure where our instructions are lacking.

I'm closing this, but you can reopen if you're still having problems. Thanks!
