### ISSUE TITLE
all-your-base has an incorrect test case

### ISSUE THREAD

**Issue by anupamsobti** [exercism/cpp#280]
The [test case](https://github.com/exercism/cpp/blob/master/exercises/all-your-base/all_your_base_test.cpp#L105) `leading_zeros` is incorrect in my opinion.
Also, I think it might be better that the invalid cases throw an std::error instead of returning 0.

**Comment by patricksjackson** [comment]
We typically take our test cases from a central repo for exercism - https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json

In this case you are absolutely right, `leading_zeros` should return [4, 2], I must have missed that when I reviewed it.

Also I agree, returning std::error would be much better than returning 0, especially since 0 is a valid return value.

Would you like to make those changes to the test suite?

**Comment by anupamsobti** [comment]
Sure. I'll do that. Should I also make changes to the canonical-data.json since the std::error would be a change in the same?

**Comment by patricksjackson** [comment]
The canonical tests already note that the return value for some of the tests is an error. Those are the ones that should be throwing a std::error, so I don't think you need to change that.

**Comment by anupamsobti** [comment]
I found this on Wikipedia. It seems there does exist a [unary numeral system](https://en.wikipedia.org/wiki/Unary_numeral_system). I'm thinking I would just check the length of the vector in the test case irrespective of the symbol used (0 or 1). A base 0 would still throw an std::error.

**Comment by patricksjackson** [comment]
If you want to add unary to the test cases you need to do that in the [problem specifications repo](https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json), but I doubt they will want to add that since it is distinctly different from how the other bases work.

That central place exists so that all the different languages on Exercism can share the load of creating good test suites, and adding something like this is exactly the type of discussion that they have. In this language track I don't want to deviate from the tests listed there unless we hit a language specific edge case.

**Comment by anupamsobti** [comment]
I thought so. Let me create another pull request to just add the std::error and fix the `leading_zeros` test case. I'll raise a separate issue for the unary number system.

**Comment by patricksjackson** [comment]
Cool, sounds good 👍

**Comment by anupamsobti** [comment]
I did that in #282 . Although, [some build](https://travis-ci.org/exercism/cpp/builds/534457814?utm_source=github_status&utm_medium=notification) seems to be failing. I'm not sure how to fix that. Can you guide me?

**Comment by patricksjackson** [comment]
Right, I noted int he PR that you need to fix the example. We have a confusing setup here, where we keep an example solution for testing and is sometimes used as 'advice' for mentors to get a reference on how to actually do a problem. You'll need to update the example (in example.cpp and example.h) to pass the tests.

Some of that is explained here, and also explains how to test locally: https://github.com/exercism/cpp#testing-an-exercise
