### ISSUE TITLE
visual c++ error main.exe not found

### ISSUE THREAD

**Issue by manan3172003** [exercism/cpp#291]
Hi! I  am new to learning C++ and was having an error while making a project with two files. The error is:  
"error LNK2019: unresolved external symbol "int __cdecl getInteger(void)" (?getInteger@@YAHXZ) referenced in function main"

can anyone help I have been stuck for days. Thanks in advance!

`https://gist.github.com/manan3172003/9f14b31380a0f2c6cf63c39722e23e34`

**Comment by patricksjackson** [comment]
A better place to ask would probably be StackOverflow, but I'll try to help. If you need more help I suggest asking there.

It seems like you didn't add the second file correctly, or Visual Studio isn't setup correctly, since you're having linker errors.

To learn the basic concepts, maybe take a look at [Learn C++](learncpp.com). The issue you've encountered is (at least partially) that you need a header file with a declaration for the `getinput()` function. [This page](https://www.learncpp.com/cpp-tutorial/header-files/), in particular the part on "Writing your own Header Files", should help explain.

To work with Visual Studio, I suggest following [the tutorials here](https://tutorials.visualstudio.com/), specifially "Build your first C++ App" and "Build a calculator with C++". The calculator one will demonstrate how to work with multiple files.
