### ISSUE TITLE
Extremely long build time with CMake on Windows

### ISSUE THREAD

**Issue by ducmtran** [exercism/cpp#301]
I am trying to build a hello world program from the C++ track and CMake take a very long time to build and run the test (2-3 minutes). I am new with C++ and CMake so I don't know if there is something very obvious that I'm missing.

I'm using VSCode on Windows and this happend both when I use the CMake Tools extension or run CMake from the terminal manually

[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/MinhDuc/Documents/Programming/exercism/cpp/hello-world/build --config Debug --target all -- -j 6
[build] Scanning dependencies of target hello-world
[build] [ 50%] Building CXX object CMakeFiles/hello-world.dir/hello_world_test.cpp.obj
[build] [ 75%] Building CXX object CMakeFiles/hello-world.dir/hello_world.cpp.obj
[build] [ 75%] Building CXX object CMakeFiles/hello-world.dir/test/tests-main.cpp.obj
[build] [100%] Linking CXX executable hello-world.exe
[build] [100%] Built target hello-world
[build] Build finished with exit code 0

The process takes a very long time at the "Linking CXX..." step

**Comment by KevinWMatthews** [comment]
Hi @ducmtran ,

Does the build take as long if you run it a second time?

For example, the first build takes just over a minute on my box. Subsequent builds are less than a second.

The first compile is long because the compiler has to build the *test framework itself*, the specific tests, and your solution. Subsequent compiles should be quick because the compiler only rebuilds the tests and your solution.

I remember that the test framework that we're using, [catch2](https://github.com/catchorg/Catch2), is pretty large for a single file. It's almost [15,000 lines long](https://github.com/exercism/cpp/blob/master/exercises/hello-world/test/catch.hpp).... Exactly how long it takes to build will depend on your PC/OS/compiler/etc.

This does mean that you will want to be cautious about "cleaning" the project. A clean deletes *everything* that was compiled and starts from scratch, so it will recompile the test framework.

You will also want to avoid editing files in the `test/` subdirectory (that's the test framework), but you really shouldn't need to.

Hope that helps!

**Comment by ducmtran** [comment]
@KevinWMatthews do you mean subsequent builds as in "no modifications are made"?

So if I rebuild again without any changes to the file then it output the result instantly, but if I change something in the hello_world.cpp file then it takes just as long again. I do not touch the /test folder at all.

This happens to me for both the gcc 7.3.0 and gcc 9.1.0 (latest I think). I did see that the catch framework is pretty huge. So I guess that's the reason why then. I have not done much C/C++ with such huge library so I have no idea what the expected build time is like

I work on my laptop, which I feel like is pretty decent for light programming. I worked with SDL2 in C before and did some lightweight Android app dev without any issue so I really feel like it should not take that long to run and test a Hello World program (even consider in the framework)

Do you think using Visual Studio as the instructions would be significantly faster?

**Comment by patricksjackson** [comment]
The CMake should be configured so that it does rebuild the test framework more than once, but it sounds like it might be hanging for you when it's linking, which does have to happen on every compile.

As suggested in your discussion with the VSCode extension - https://github.com/microsoft/vscode-cmake-tools/issues/727, it sounds like it's the compiler taking a long time with Catch, and using Visual Studio would be faster.

I assume you're using GCC running on Windows and not on WSL? I want to test it.

**Comment by ducmtran** [comment]
@patricksjackson I posted there about the issue but I did later realize that it's not an issue with the extension. How did you find out about the issue I posted over there? (I'm new to github discussion :)

Yes I use gcc on windows, not WSL.

**Comment by patricksjackson** [comment]
I was snooping on your profile, and issues you opened get listed there.

I'll take a look, but probably it's just that GCC on Windows takes a long time to link the test framework and there isn't going to be a fix, so using Visual Studio would be faster.

**Comment by patricksjackson** [comment]
I forgot that GCC doesn't have a real Windows version, and is only through MinGW or Cygwin. If you installed it through Cygwin that definitely explains it, and MinGW is also likely to have issues.

The [native Clang](http://releases.llvm.org/download.html) should work better, but it'd be just as easy to use MSVC. You can always install the Visual Studio compiler and use it through CMake tools in VSCode. That will probably give you fewer issues than using Clang.
