### ISSUE TITLE
Inconsistency Between Exercise Name and Source Files

### ISSUE THREAD

**Issue by Nolshine** [exercism/cpp#303]
Exercise names that consist of more than one word will usually have their names hyphenated, but the CMake config will have CMake looking for source files with words separated by underscores. 

E.g.: 
Exercise name "space-age" will have CMake looking for "space_age.h" and "space_age.cpp"

Not only is this really annoying, because one has to figure out why CMake isn't finding the files, which isn't immediately obvious, it's also inconsistent, which is bad practice.
I suggest having the exercise names use underscores instead, or having CMake look for source files whose names are hyphenated instead.

**Comment by KevinWMatthews** [comment]
True, point taken.

This naming convention ('`-`' for directories and '`_`' for filenames) has been around for quite awhile: at least [5 years](https://github.com/exercism/cpp/commit/c155f9f6f47e2fa8cf8a1f0644bed8d19a21c5c0) in some cases.

@patricksjackson Do you have any feedback on this?

**Comment by patricksjackson** [comment]
I understand the annoyance here, but it is our convention. My assumption is that at some point Exercism required the directory names to be dashes, and the original track creator wanted to use underscores for the file names.

I think the specific issue here will go away entirely after we add the stubs #300.

**Comment by NobbZ** [comment]
> My assumption is that at some point Exercism required the directory names to be dashes, …

It still does so. Exercises needs to have the same name as in the "central library", such that they get their icons. The folder names need to match the exercises name from the `config.json`.

The canonical data and all other places throughout exercism assume dashed slugs.

And from all what I have seen, it seems as if in C and C++ underscored filenames have been prefered all over the place. A professor of mine assumed thats because filenames resemble the look of identifiers then and in C++ could even match their namespace.

**Comment by Nolshine** [comment]
Fair enough, I have little knowledge of Cpp-specific conventions and zero knowledge of how exercism needs to work.
