### ISSUE TITLE
I have stopped receiving feedback

### ISSUE THREAD

**Issue by tedvash** [exercism/cpp#310]
I have used Exercism for several (~10) exercises in total.
Feedback was very prompt initially (and I must say, very helpful).
But I have not received any feedback in over 3 weeks now on several C++ exercises in the cpp track.

**Comment by tedvash** [comment]
My account/email is cosmicvisitor@hotmail.com

**Comment by siebenschlaefer** [comment]
First, some statistics:

At this moment there are 29 exercises in the queue, 6 core exercises (the oldest is 4 days old), and 23 side exercises (the oldest is 22 days old).

There are four exercises from "cosmicvisitors" in the queue:
- [Sieve](https://exercism.io/mentor/solutions/61526b867d77489883139aa838d7e442), submitted 17 days ago
- [Nth Prime](https://exercism.io/mentor/solutions/03d0eb506d7f4fb188c717e87385b840), submitted 5 hours ago
- [Queen Attack](https://exercism.io/mentor/solutions/936f31f99968457f992d7cb58b67eedf), submitted 4 hours ago
- [Space Age](https://exercism.io/mentor/solutions/108a9c3b19944392adfe192e6e1dd46d), submitted 1 hour ago

In the last three weeks 232 solutions were reviewed.

I *believe* that the C++ track looks really good in comparison to the more popular ones. Someone mentioned in the chat that a few days ago that there were 49 solution in the JavaScript track awaiting review - for the "resistor color" exercise alone!

Second, my personal view:

I think most mentors (including me) give preference to the core exercises. They very rarely get older than seven days.  
I don't pick the first solution in the queue. There are exercises that I can review in less than five minutes. But there are some exercises that I avoid. I don't like "Bob", "Say", or "Crypto Square", and I hope that somebody else reviews those.  
We mentors are volunteers and we pick the exercises we *want* to review. That means some solutions that are uncomfortable to review just lay around ageing until someone has mercy.

Last not least: I want to help students write bug free, readable, idiomatic, and reasonably efficient code. In the last exercise of you that I mentored you expressed that you don't want to spend time on researching an efficient algorithm, you were more interested in language constructs. That's a valid goal, but I don't think I would be a good mentor for that because IMHO choosing the right algorithm is an important aspect of the solution, and out goals are just different.

**Comment by tedvash** [comment]
Sounds like a misunderstanding, have sent you an email to discuss offline...

**Comment by KevinWMatthews** [comment]
Hi @tedvash, hope you get things clarified. If you resolve things offline, please let us know and we'll close this issue.

If you need more help later, just let us know. Depending on the details of your issue, we might refer you to elsewhere in the Exercism ecosystem - this repo is typically focuses on exercise source code. Regardless, feel free to ping us here and we'll figure out how to help.

**Comment by tedvash** [comment]
@siebenschlaefer Matthias, I emailed you at webding.de, did you receive it?

**Comment by tedvash** [comment]
Thanks for the help everyone. I suggest we close the ticket...

I am a new user and I think I got a bit carried away with my expectations. I understand how it works a bit better now. Thanks!

**Comment by KevinWMatthews** [comment]
@tedvash Sounds good. Thanks!
