### ISSUE TITLE
Boost dist version on Travis CI

### ISSUE THREAD

**Issue by tqa236** [exercism/cpp#323]
Currently, the Ubuntu version on Travis CI is trusty. Considering that it's a quite old version that already reached its end of life, should we boost the version into xenial or bionic?

**Comment by patricksjackson** [comment]
I didn't realize they supported newer than trusty. It looks like they started supporting Xenial (16.04) a year ago.

I'll bump it up to 16.04, since that is the minimum version we explicitly support in the docs.

Thanks!

**Comment by tqa236** [comment]
Thank you very much. And what do you mean by "they"?

**Comment by heitorPB** [comment]
Why downgrade boost?

**Comment by patricksjackson** [comment]
@tqa236 "they" = Travis CI. They didn't support Xenial until last year - https://blog.travis-ci.com/2018-11-08-xenial-release

@heitorPB I reduced the required version for Boost in the PR because the features in Boost that we use are already present in v1.58. I think the features are available even earlier actually but I haven't tested. This also means that any student still on Ubuntu 16.04 can just install `libboost-date-time-dev` from the normal Ubuntu repos and everything will work.

The required Boost version should have been lowered when we switched to using Catch2 for testing, but we didn't check.

**Comment by tqa236** [comment]
I think Travis CI also has Bionic - https://docs.travis-ci.com/user/reference/bionic/. How do we know if they also support Bionic or not?

**Comment by patricksjackson** [comment]
They do have Bionic (and apparently they finally got around to adding Windows and OSX support). I added Bionic to run on the 'latest' configs, but I won't spend much time on it since I'd rather switch to the Github Actions config when it exits Beta.

Github Actions is already running against Windows and OSX in addition to the 4 different Linux configs that we also run on Travis.
