### ISSUE TITLE
Changing compilation for all exercises

### ISSUE THREAD

**Issue by elyashiv** [exercism/cpp#355]
Inspired by #354 - if one needs to change the way we compile all exercises, how will this be checked? How would we know the change happened to all exercises, and will get also to future ones?

When I opened the mentioned PR, I checked the number of changed files against the number of exercises, just to be sure. But this won't change existing PR, nor did I create a CI test.

Any thought on the subject?

**Comment by Llcoolsouder** [comment]
Could we change our structure up a bit? 
I imagine all of our exercises are using almost identical CMakeLists.txt files with the exception of the source file names. Could we just have 1 cmake file that defines a macro that reflects this and have all of the individual exercises call this macro with the source names?

**Comment by elyashiv** [comment]
I would guess the problem is with exercism, not the CI. When a student pulls an exercise, he gets a copy of the folder. So, if you have a file with a macro, the student will need to fetch it as well.

I wander if a symbolic link will do the trick.

Or maybe change the way exercism works so there is some template to derive the file from?

**Comment by patricksjackson** [comment]
Yes, the reason there are copies is because the Exercism cli doesn't support a way for us to download a 'dependency' folder or similar for users. It's been a known request for years, and with the move to v3 this repo will be mostly deprecated so it is not really worth fixing.

I'm not sure if a symbolic link would work, but that's a good idea. It'd have to be handled correctly by git and the Exercism cli tool (the tool would have to download the linked file, and not the link itself, maybe a hard link?).

The other option is just writing a check in CI to make sure they're all identical, which shouldn't be too difficult.

Another thing in a similar vein, we have the catch.hpp file in each folder as well. In v3 someone updated the CMake config to download the Catch file rather than keeping it in git, but again I assume it isn't really worth it to change things here if v3 is deprecating these anyways.

**Comment by patricksjackson** [comment]
Closing this, there may be some tooling we could write to ensure everything stays in sync, but fundamentally we can't get away from having to have a separate copy of the build system in each separate exercise.
