### ISSUE TITLE
Mac M1 binary created doesn't run

### ISSUE THREAD

**Issue by rohansood42** [exercism/cpp#497]
I was trying to run the test cases after using make. The executable doesn't seem to work on my M1 Mac.

`bash: ./run_unit_tests: cannot execute binary file`

Any help?

**Comment by patricksjackson** [comment]
Nothing in this repo builds a file called "run_unit_tests", so I don't know what you're trying to do. Are you using XCode? Makefiles? Did you see any errors in compilation? What steps did you take/commands did you try?

People are successfully using this on M1 Macs. There was an issue on M1 Macs with compilation errors in #432, which was fixed with #433. If that's the issue you're having then you need to update the version of your exercises using the website.

Closing this since there's no info, please add information about your test environment or errors if you still need any help.
