### ISSUE TITLE
Error with cmake on gigasecond exercies.

### ISSUE THREAD

**Issue by zberwaldt** [exercism/cpp#532]
Hello,

I've been trying to set up the gigasecond exercise for this track and I've been getting an error trying run cmake.

Steps to recreate: 

1. ` exercism download --exercise=gigasecond --track=cpp`
2. `cd ./gigasecond`
3. `cmake -G "Unix Makefiles" -DEXERCISM_RUN_ALL_TESTS=1`

Outpute:
```
CMake Error at /usr/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR date_time) (Required is at
  least version "1.58")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.21/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)
  CMakeLists.txt:13 (find_package)```
  
  Let me know if you need more information.

**Comment by patricksjackson** [comment]
I'm going to go ahead and assume you've already tried installing the Boost libs, since the error message clearly states it's missing, [the comments at the top of the test file](https://github.com/exercism/cpp/blob/17660ebd6bfb2060b80b7a509101e32c715712e9/exercises/practice/gigasecond/gigasecond_test.cpp#L9) tell you it's required, and a search of Issues on this repo mention it numerous times.

It would help if you shared what OS you are using and how you installed Boost, since some distros have confusing package names for it (you'll need the development packages, Ubuntu for example is `libboost-dev` I think). We've also had some issues on the BSDs in the past, but I think we'd fixed those at this point.

If you do get stuck installing it then please use the web editor for Gigasecond and Meetup, or just skip them, as those are the only two exercises still requiring Boost.

**Comment by zberwaldt** [comment]
Sorry to bother you. 👍
