### ISSUE TITLE
Add practice exercise for linked list

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#566]
The #12in23 challenge asks to do the linked-list exercise, which is currently not implemented and should be added during the month of March.

**Comment by siebenschlaefer** [comment]
Does the self-assignment mean you're working on it?
Otherwise I'll give it a try.

**Comment by vaeng** [comment]
> Does the self-assignment mean you're working on it? Otherwise I'll give it a try.

Yes, I have started to add some basic files, but have not yet done more (the instruction are taken from the Go track). Feel free to add more.

 One of the thoughts I wanted to discuss was the split with .cpp and header files. And if we should move the "easy" exercises to "cpp-only" to nudge the students slowly to that topic on later exercises that need more organization.

**Comment by siebenschlaefer** [comment]
Some notes:

- `push()`, `pop()`, `unshift()`, and `shift()` are mandatory, `delete()` and `count()` are optional. Do we want them?  
    I'd vote yes but then we need an additional markdown file that describes them, similarly to the description of the mandatory functions.
- The tests leave it to the tracks whether `delete()` should return the first or last matching element (or leave it unspecified). What do we want? I'd vote first.
- Do we want other C++-specific things? Should the linked-list class be a class template? Do we want iterators? Do we want an exception if `pop()` or `shift()` get called on an empty list? Should `count()` be named `size()`? Tracks are allowed to add/change things when its reasonable and idiomatic.

Attached is a Python script [create_tests.txt](https://github.com/exercism/cpp/files/10864339/create_tests.txt) that reads the `canonical-data.json` (from the problem-specification repository) and prints the contents of the `linked_list_test.cpp`. (It ends with `.txt` because GitHub does not allow attaching `.py` files.)

**Comment by vaeng** [comment]
You do make some very good points. I think we should definitely do a `simple-linked-list` first. The way I see it, it is intended to have elements with int-data, push, pop, size, reverse and an array conversion. That would pave the way to have the "advanced" version as class template with iterators. What do you think @siebenschlaefer?

**Comment by siebenschlaefer** [comment]
I just wanted to list these considerations explicitly so that others can weigh in.
I'm completely fine with a simple non-template `LinkedList` class without exceptions that has these six methods.

From a mentoring perspective I expect the conversations to the about memory management (naked `new` and raw pointers versus smart pointers a non-recursive deletion), about the general approach of the implementation (first/last pointers or a dummy node), and about helper functions/DRY. At least that's my experience for the linked-list exercise on the C track.

**Comment by vaeng** [comment]
That's very valuable insight. As the memory aspects with pointer management can be a bit intimidating, the related exercises should not do much else.

But, with the memory management questions mostly answered with the simple-list, we could dive into a nice iterator solution and make them useful via templates.
